Introduction
Alp4ga/SQA_Assignment_1 pull request #3
Opened 2021-03-18 16:10 UTC by Alp4ga

- Create new file Handbook.md
- Write introduction
- Write all part of the documents with Table of contents

2021-03-18 16:52 UTC, Az8th requested changes
Rewiew : content ok. Two typos to fix before merging

2021-03-18 16:52 UTC, Az8th commented on Handbook.md
> +conditions and pratices you must follow.
practices

2021-03-18 16:52 UTC, Az8th commented on Handbook.md
> +You will learn about Task estimation in scrum process. The coding standars you must follow to help your co-workings understanding your code.
standards

2021-03-18 16:56 UTC, Alp4ga reviewed
The new typo seems mutch better

2021-03-18 17:20 UTC, Az8th approved these changes

2021-03-20 10:47 UTC, BetaTuX approved these changes

2021-03-20 10:48 UTC, merged