Task estimation topic
Alp4ga/SQA_Assignment_1 pull request #8
Opened 2021-03-28 20:38 UTC by BetaTuX

2021-03-30 16:45 UTC, Alp4ga commented
Il faut que tu passe par la branch Develop chef

2021-03-30 16:46 UTC, Alp4ga requested changes
You must merge request on develop branch

2021-04-01 15:19 UTC, Alp4ga approved these changes

2021-04-03 18:00 UTC, Az8th requested changes
Seems good but typos needs to be fixed

2021-04-03 18:00 UTC, Az8th commented on Handbook.md
> +It will help you find an smart solution and estimate your time accurately.
```suggestion
It will help you find a smart solution and estimate your time accurately.
```

2021-04-03 18:00 UTC, Az8th commented on Handbook.md
> +Very differents solutions exist in this regard, it ranges from simple Kanban board tools to a very complex cluster of various tools in order to have a complete overview of the task, the time estimati
```suggestion
Very different solutions exist in this regard, from simple Kanban board tools to a very complex cluster of various tools in order to have a complete overview of the task, the time estimation, the progress and the different unforeseen issues that the support service will give as feedback for us.
```

2021-04-03 18:00 UTC, Az8th commented on Handbook.md
> +That's why other complex solutions are available for bigger project.
```suggestion
That's why other complex solutions are available for bigger projects.
```

2021-04-03 18:00 UTC, Az8th commented on Handbook.md
> +If you're project is simple, and doesn't need a long-time support, a simple Kanban board as Trello of the board in GitLab tool is enough.
```suggestion
If your project is simple, and does not need a long-time support, a simple Kanban board as Trello of the board in GitLab tool is enough.
```

2021-04-03 18:00 UTC, Az8th commented on Handbook.md
> +On the other hand, if your solution needs a better overview of the multiple tasks and have also a crucial need of support in the long run, more complex tools as Jira should be considered.
```suggestion
On the other hand, if your solution needs a better overview of the multiple tasks and also have a crucial need of support in the long run, more complex tools as Jira should be considered.
```

2021-04-03 18:00 UTC, Az8th commented on Handbook.md
> +When it comes to the technic and how to foresee the time estimation, it pretty much always come down to experience.
```suggestion
When it comes to the technique and how to foresee the time estimation, it pretty much always come down to experience.
```

2021-04-03 18:01 UTC, Az8th approved these changes

2021-04-03 18:05 UTC, merged